# Build Stage
FROM node:20-alpine AS builder

WORKDIR /app


ARG VITE_API_URL=/api
ENV VITE_API_URL=$VITE_API_URL

COPY client/package*.json ./
RUN npm ci --frozen-lockfile

COPY client/ .
RUN npm run build

#Runtime Stage 
FROM nginx:alpine AS runtime

# Copy built assets from builder
COPY --from=builder /app/dist /usr/share/nginx/html

# Copy custom nginx config
COPY nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
